### ISSUE TITLE
Switch to using azure rtos from the official repo

### ISSUE THREAD

**Issue by JakeSays** [Azure-Samples/Azure-RTOS-on-Azure-Sphere-Mediatek-MT3620#1]
This sample uses a copy of the official repo. Please change it to use the official repo instead.

Since most of us will be building real products we won't be using a version of az rtos that is tied to sample code. Having the two not match is much less useful.

**Comment by liydu** [comment]
Thanks @kartben for helping submodule the official repo. 

Resolved in #4
